import { randomUUID } from "node:crypto";
import { Router } from "express";
import { env } from "../config/env.js";
import { supabaseAdmin } from "../db/supabase.js";
import { requireUser } from "../auth/auth.js";
import { hasStoredUpworkToken, saveUpworkToken } from "../integrations/upwork-token-store.js";
export const upworkIntegrationRouter=Router();
function oauthConfigured(){return Boolean(env.UPWORK_CLIENT_ID&&env.UPWORK_CLIENT_SECRET&&env.UPWORK_REDIRECT_URI&&env.OAUTH_ENCRYPTION_KEY);}
async function authorizationUrl(userId:string){if(!oauthConfigured())throw new Error("Upwork OAuth environment variables are not configured.");const state=randomUUID();const{error}=await supabaseAdmin.from("oauth_states").insert({state,user_id:userId,provider:"upwork",expires_at:new Date(Date.now()+600000).toISOString()});if(error)throw error;const url=new URL("https://www.upwork.com/ab/account-security/oauth2/authorize");url.searchParams.set("response_type","code");url.searchParams.set("client_id",env.UPWORK_CLIENT_ID!);url.searchParams.set("redirect_uri",env.UPWORK_REDIRECT_URI!);url.searchParams.set("state",state);return url.toString();}
upworkIntegrationRouter.get("/status",requireUser,async(req,res,next)=>{try{res.json({configured:oauthConfigured(),connected:await hasStoredUpworkToken(req.user!.id)});}catch(e){next(e);}});
upworkIntegrationRouter.get("/connect-url",requireUser,async(req,res,next)=>{try{res.json({authorizationUrl:await authorizationUrl(req.user!.id)});}catch(e){next(e);}});
upworkIntegrationRouter.get("/callback",async(req,res)=>{try{const code=typeof req.query.code==="string"?req.query.code:"";const state=typeof req.query.state==="string"?req.query.state:"";const{data,error}=await supabaseAdmin.from("oauth_states").select("user_id,expires_at").eq("state",state).eq("provider","upwork").maybeSingle();await supabaseAdmin.from("oauth_states").delete().eq("state",state);if(error)throw error;if(!code||!data||new Date(data.expires_at).getTime()<Date.now())throw new Error("Invalid or expired Upwork OAuth state.");const body=new URLSearchParams({grant_type:"authorization_code",client_id:env.UPWORK_CLIENT_ID!,client_secret:env.UPWORK_CLIENT_SECRET!,code,redirect_uri:env.UPWORK_REDIRECT_URI!});const response=await fetch("https://www.upwork.com/api/v3/oauth2/token",{method:"POST",headers:{Accept:"application/json","Content-Type":"application/x-www-form-urlencoded"},body,signal:AbortSignal.timeout(15000)});if(!response.ok)throw new Error(`Upwork token exchange failed (HTTP ${response.status}).`);await saveUpworkToken(data.user_id,await response.json() as any);return res.redirect(`${webOrigin()}/?upwork=connected`);}catch(error){return res.redirect(`${webOrigin()}/?upworkError=${encodeURIComponent(error instanceof Error?error.message:"Upwork OAuth failed")}`);}});
function webOrigin(){return env.WEB_ORIGIN.split(",")[0].trim().replace(/\/$/,"");}
