import { createGenericAgent } from "./agent.js";
const v="2.0.0";
export const genericAgents=[
createGenericAgent({meta:{id:"lead-research",name:"Lead Research Agent",shortName:"Prospector",icon:"search",version:v,category:"sales",description:"Turns a target niche into a qualified lead-research plan and prospect criteria.",purpose:"Build a focused outbound pipeline without random prospecting."},role:"a B2B lead researcher",objective:"find companies likely to need the company's services",workflow:["Define ICP and trigger signals","Prioritize lead sources","Research pains and buying signals","Score prospects","Prepare personalized outreach angles"]}),
createGenericAgent({meta:{id:"outreach",name:"Outreach Agent",shortName:"Reach",icon:"send",version:v,category:"sales",description:"Creates truthful, personalized outreach and follow-up sequences.",purpose:"Start sales conversations without generic spam."},role:"a B2B outbound specialist",objective:"turn researched leads into relevant conversations",workflow:["Identify strongest reason to contact","Choose channel and opening","Write concise personalized message","Prepare follow-up sequence","Define reply handling"],draftKind:"outreach message"}),
createGenericAgent({meta:{id:"client-discovery",name:"Client Discovery Agent",shortName:"Discover",icon:"dialog",version:v,category:"sales",description:"Prepares discovery calls, questions, scope gaps and buying signals.",purpose:"Understand the real problem before pricing or building."},role:"a senior software discovery consultant",objective:"turn vague client requests into clear business and delivery understanding",workflow:["Map stakeholders and users","Separate goals from requested features","Identify unknowns and dependencies","Prepare discovery questions","Define decision and next step"]}),
createGenericAgent({meta:{id:"estimator",name:"Estimator Agent",shortName:"Estimate",icon:"calculator",version:v,category:"sales",description:"Builds effort, pricing and milestone estimates with explicit assumptions.",purpose:"Price projects consistently without guessing."},role:"a software delivery estimator",objective:"produce defensible scope and pricing guidance",workflow:["Break scope into workstreams","List assumptions and unknowns","Estimate effort ranges","Add risk contingency","Recommend milestone and pricing structure"]}),
createGenericAgent({meta:{id:"requirements",name:"Requirements Agent",shortName:"Spec",icon:"list",version:v,category:"delivery",description:"Turns project context into requirements, stories and acceptance criteria.",purpose:"Give design and development a shared definition of done."},role:"a software product analyst",objective:"produce implementable requirements and acceptance criteria",workflow:["Identify user roles","Map core journeys","Write functional requirements","Capture edge cases","Define acceptance criteria"]}),
createGenericAgent({meta:{id:"delivery-qa",name:"Delivery QA Agent",shortName:"Guardian",icon:"shield",version:v,category:"delivery",description:"Creates release checks, QA coverage and handover criteria.",purpose:"Reduce avoidable defects and weak client handovers."},role:"a pragmatic software QA and release lead",objective:"make delivery reliable and reviewable",workflow:["Identify critical user journeys","Create functional test matrix","Check security and error states","Prepare release checklist","Prepare handover checklist"]}),
createGenericAgent({meta:{id:"marketing-growth",name:"Marketing & Growth Agent",shortName:"Growth",icon:"megaphone",version:v,category:"growth",description:"Plans positioning, content and demand-generation experiments.",purpose:"Give the company a repeatable marketing direction."},role:"a B2B software growth strategist",objective:"generate qualified demand for the company's services and products",workflow:["Clarify audience and positioning","Choose acquisition channels","Create weekly content/outreach plan","Define experiments","Set measurable indicators"]}),
createGenericAgent({meta:{id:"client-growth",name:"Client Growth Agent",shortName:"Expand",icon:"grow",version:v,category:"growth",description:"Finds retention, support, upsell and referral opportunities from delivered work.",purpose:"Increase value from successful client relationships."},role:"a client success and account growth lead",objective:"retain clients and identify ethical expansion opportunities",workflow:["Review delivered value","Identify ongoing operational needs","Propose support or improvement opportunities","Prepare check-in conversation","Ask for referral/case study at the right time"]}),
createGenericAgent({meta:{id:"case-study",name:"Case Study Agent",shortName:"Proof",icon:"document",version:v,category:"growth",description:"Turns completed work into truthful portfolio and case-study material.",purpose:"Convert delivery into proof that wins future work."},role:"a B2B case-study writer",objective:"create credible proof from completed software work",workflow:["Capture client situation","Document work actually delivered","Identify measurable or observable outcomes","Build before/after narrative","Create portfolio and social versions"],draftKind:"case study"}),
createGenericAgent({meta:{id:"operations",name:"Operations Agent",shortName:"Ops",icon:"gear",version:v,category:"operations",description:"Turns recurring company work into simple SOPs, checklists and ownership.",purpose:"Reduce founder bottlenecks and operational memory."},role:"a small software-company operations lead",objective:"make recurring work repeatable and delegable",workflow:["Identify recurring process","Define trigger and owner","Write minimum SOP","Add quality checks","Define escalation path"]}),
createGenericAgent({meta:{id:"company-advisor",name:"Company Advisor Agent",shortName:"Advisor",icon:"compass",version:v,category:"operations",description:"Evaluates company decisions against revenue, capacity and focus.",purpose:"Help the founder make structured trade-offs."},role:"a practical software-company operating advisor",objective:"improve decisions without adding unnecessary complexity",workflow:["State decision and desired outcome","List constraints","Compare realistic options","Identify downside risks","Recommend next reversible action"]})
];
